/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
 
/**
 *
 * @author keroles samer
 */
import java.sql.Time;
import java.util.Date;
import opnsrc.fcih.trainrsys.backend.Employee;
import opnsrc.fcih.trainrsys.backend.Admin;
import opnsrc.fcih.trainrsys.backend.Train;
public class AddTrain extends javax.swing.JFrame {

    /**
     * Creates new form AddTrain
     */
    Train e;
    public AddTrain() {
        initComponents();
        e=new Train();
    }
  //Train  e=new Train();
   Admin admin =new Admin();
   Date d=new Date();
    /**
     * 
 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTrainSpeed = new javax.swing.JTextField();
        jTrainID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTrainName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jstartpoint = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jerrorvalid = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jArrivepoint = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jleavingcombo = new javax.swing.JComboBox<>();
        jarrivecombo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 31, -1, 249));

        jTrainSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrainSpeedActionPerformed(evt);
            }
        });
        getContentPane().add(jTrainSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 150, 30));

        jTrainID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrainIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTrainID, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 150, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(248, 149, 32));
        jLabel9.setText("ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(248, 149, 32));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));
        getContentPane().add(jTrainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(248, 149, 32));
        jLabel11.setText("Leaving Time");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(248, 149, 32));
        jLabel12.setText("Source");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jstartpoint.setEditable(true);
        jstartpoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alex", "Cairo", "Aswan", "Matroh" }));
        jstartpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstartpointActionPerformed(evt);
            }
        });
        getContentPane().add(jstartpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 150, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(248, 149, 32));
        jLabel14.setText("Destnation");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(248, 149, 32));
        jLabel15.setText("Speed");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 50, 40));

        jerrorvalid.setForeground(new java.awt.Color(249, 149, 32));
        getContentPane().add(jerrorvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 150, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("save");
        jButton1.setOpaque(false);
        jButton1.setPreferredSize(new java.awt.Dimension(63, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 100, 50));

        jArrivepoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alex", "Cairo", "Aswan", "Matroh" }));
        jArrivepoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArrivepointActionPerformed(evt);
            }
        });
        getContentPane().add(jArrivepoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 149, 32));
        jLabel2.setText("Arrive Time");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 100, 30));

        jleavingcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "03:00:00", "04:00:00", "05:00:00", "06:00:00", "07:00:00" }));
        jleavingcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jleavingcomboActionPerformed(evt);
            }
        });
        getContentPane().add(jleavingcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 150, 30));

        jarrivecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01:00:00", "02:00:00", "03:00:00", "04:00:00", "05:00:00" }));
        jarrivecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarrivecomboActionPerformed(evt);
            }
        });
        getContentPane().add(jarrivecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 150, 30));

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logiiiin.jpg"))); // NOI18N
        jLabel16.setOpaque(true);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
// TODO add your handling code here:
    if ((Integer.parseInt(jTrainID.getText())<0 )|| Integer.parseInt(jTrainSpeed.getText()) < 50 || jTrainName.getText().equals("")){
        jerrorvalid.setText("un valid declariton");
    }

 admin.addNewTrian(jTrainName.getText(),Integer.parseInt(jTrainID.getText())
         ,jarrivecombo.getSelectedItem()+"", jArrivepoint.getSelectedItem()+"",
         jstartpoint.getSelectedItem()+"",jleavingcombo.getSelectedItem()+"" /*Integer.parseInt(jTrainSpeed.getText())*/ );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTrainSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrainSpeedActionPerformed
        if(Integer.parseInt(jTrainSpeed.getText())<80 && Integer.parseInt(jTrainSpeed.getText())>200){
            jerrorvalid.setText("invalid speed");  
            jTrainSpeed.setText("");
        }
        else{
        e.SetSpeed(Integer.parseInt(jTrainSpeed.getText()+""));
        jerrorvalid.setText(""); 
        } 

        // TODO add your handling code here:
    }//GEN-LAST:event_jTrainSpeedActionPerformed

    private void jTrainIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrainIDActionPerformed
                if(Integer.parseInt(jTrainID.getText())<0){
            jerrorvalid.setText("invalid ID");  
            jTrainID.setText("");
        }
        else{
        e.SetTrain_ID(Integer.parseInt(jTrainID.getText()+""));
        jerrorvalid.setText(""); 
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrainIDActionPerformed

    private void jArrivepointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArrivepointActionPerformed
        // TODO add your handling code here:
        e.SetStart_Point(jstartpoint.getSelectedItem()+"");
    }//GEN-LAST:event_jArrivepointActionPerformed

    private void jstartpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstartpointActionPerformed
        e.SetArraive_Point(jArrivepoint.getSelectedItem()+"");
    }//GEN-LAST:event_jstartpointActionPerformed

    private void jleavingcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jleavingcomboActionPerformed
        e.SetArriveTime(jleavingcombo.getSelectedItem()+"");
    }//GEN-LAST:event_jleavingcomboActionPerformed

    private void jarrivecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarrivecomboActionPerformed
       e.SetLeavingTime_sPoint(jarrivecombo.getSelectedItem()+"");
    }//GEN-LAST:event_jarrivecomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTrain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jArrivepoint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTrainID;
    private javax.swing.JTextField jTrainName;
    private javax.swing.JTextField jTrainSpeed;
    private javax.swing.JComboBox<String> jarrivecombo;
    private javax.swing.JLabel jerrorvalid;
    private javax.swing.JComboBox<String> jleavingcombo;
    private javax.swing.JComboBox<String> jstartpoint;
    // End of variables declaration//GEN-END:variables
}
