/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import opnsrc.fcih.trainrsys.backend.Employee;
import opnsrc.fcih.trainrsys.backend.Admin;
/**
 *
 * @author keroles samer
 */
public class AdminAddEmployee extends javax.swing.JFrame {
    int flag=-1;
    boolean Gender;

    /**
     * Creates new form Adn=minAddEmployee
     */
    Admin admin;
    Employee e;
    public AdminAddEmployee() {
        initComponents();
        
        setExtendedState(emolyee.MAXIMIZED_HORIZ);
        setResizable(false);
        admin =new Admin();
        e=new Employee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        JEmployeeID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JEmployeeName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMale = new javax.swing.JRadioButton();
        JFemale = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        JEmployeePassword = new javax.swing.JPasswordField();
        JEmployeeJoinDate = new com.toedter.calendar.JDateChooser();
        jerrorvalid = new javax.swing.JLabel();
        JEmployeeAdress = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        JEmployeePhone = new javax.swing.JTextField();
        jQualificationtext = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JEmployeeID.setForeground(new java.awt.Color(255, 51, 51));
        JEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 149, 32));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 63, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 149, 32));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 63, -1));

        JEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeeNameActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 149, 32));
        jLabel1.setText("joindate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 63, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(248, 149, 32));
        jLabel17.setText("Password");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 70, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(248, 149, 32));
        jLabel18.setText("Phone");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 63, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(248, 149, 32));
        jLabel19.setText("Address");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 63, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(248, 149, 32));
        jLabel20.setText("gender");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 70, 20));

        jMale.setBackground(new java.awt.Color(255, 204, 204));
        gender.add(jMale);
        jMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMale.setForeground(new java.awt.Color(248, 149, 32));
        jMale.setText(" Male");
        jMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 150, 30));

        JFemale.setBackground(new java.awt.Color(255, 204, 204));
        gender.add(JFemale);
        JFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JFemale.setForeground(new java.awt.Color(248, 149, 32));
        JFemale.setText(" female");
        JFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(JFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 150, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 100, 39));

        JEmployeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, 30));
        getContentPane().add(JEmployeeJoinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 150, 30));

        jerrorvalid.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jerrorvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 150, 30));

        JEmployeeAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeeAdressActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeeAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 150, 30));

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 150, 30));

        JEmployeePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeePhoneActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 150, 30));

        jQualificationtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQualificationtextActionPerformed(evt);
            }
        });
        getContentPane().add(jQualificationtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(248, 149, 32));
        jLabel5.setText("Qualifiction");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 80, 30));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logiiiin.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JEmployeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeePasswordActionPerformed
         if((JEmployeePassword+"").length()<8) {
            jerrorvalid.setText("invalid PASSWORD");  
            JEmployeePassword.setText("");
        }
         else{
        e.setPassword(JEmployeeID.getText()+""); 
          jerrorvalid.setText("");
         }       // TODO add your handling code here:
    }//GEN-LAST:event_JEmployeePasswordActionPerformed

    private void JEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeeIDActionPerformed
        if(Integer.parseInt(JEmployeeID.getText())<0){
            jerrorvalid.setText("invalid ID");  
            JEmployeeID.setText("");
        }
        else{
        e.setUserName(Integer.parseInt(JEmployeeID.getText()+""));
        jerrorvalid.setText(""); 
        } 
    }//GEN-LAST:event_JEmployeeIDActionPerformed

    private void JEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeeNameActionPerformed
        // TODO add your handling code here:
        e.setName(JEmployeeName.getText());
    }//GEN-LAST:event_JEmployeeNameActionPerformed

    private void JEmployeeAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeeAdressActionPerformed
        // TODO add your handling code here:
        e.setAdress(JEmployeeAdress.getText());
    }//GEN-LAST:event_JEmployeeAdressActionPerformed

    private void JEmployeePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeePhoneActionPerformed
        if((JEmployeePhone.getText()+"").length()!=11) {
            jerrorvalid.setText("invalid phone");  
            JEmployeePhone.setText("");
        }
        else{
        e.setPhone(JEmployeeID.getText()+"");
         jerrorvalid.setText(""); 
        }
    }//GEN-LAST:event_JEmployeePhoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(JEmployeePhone.getText().equals("") || JEmployeeID.getText().equals("") || JEmployeeAdress.getText().equals("") ||JEmployeeName.getText().equals("") || flag==-1||(JEmployeePhone.getText()+"").length()!=11 || (Integer.parseInt(JEmployeeID.getText())<0) || (JEmployeePassword.getText()).length()<8 || ((Integer.parseInt(jQualificationtext.getText())>30 && Integer.parseInt(jQualificationtext.getText())<-1))){
    
            jerrorvalid.setText("invalid Data Entry");  
        }
        else {
            e.loadFromFile();
        if(e.getEmployeeIndex(Integer.parseInt(JEmployeeID.getText()))==-1){ 
        jerrorvalid.setText("");
        admin.addNewEmployee(
                Integer.parseInt(JEmployeeID.getText())
                ,JEmployeeName.getText()
                ,Gender, JEmployeePassword.getText()
                ,JEmployeePhone.getText()
                ,JEmployeeAdress.getText()
                ,Integer.parseInt(jQualificationtext.getText()));
          jerrorvalid.setText("");
        }
        }
        jerrorvalid.setText("this id is alreay exist");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaleActionPerformed
           flag=1;
        Gender=true;
    }//GEN-LAST:event_jMaleActionPerformed

    private void JFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFemaleActionPerformed
        // TODO add your handling code here:
        flag=2;
        Gender=false;
    }//GEN-LAST:event_JFemaleActionPerformed

    private void jQualificationtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQualificationtextActionPerformed
       if(!(Integer.parseInt(jQualificationtext.getText())>30 && Integer.parseInt(jQualificationtext.getText())<-1)){
          jerrorvalid.setText("un vaild");
       }
         else{  
           e.setQualifiction(Integer.parseInt(jQualificationtext.getText()));
       }
    }//GEN-LAST:event_jQualificationtextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JEmployeeAdress;
    private javax.swing.JTextField JEmployeeID;
    private com.toedter.calendar.JDateChooser JEmployeeJoinDate;
    private javax.swing.JTextField JEmployeeName;
    private javax.swing.JPasswordField JEmployeePassword;
    private javax.swing.JTextField JEmployeePhone;
    private javax.swing.JRadioButton JFemale;
    public static javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jMale;
    private javax.swing.JTextField jQualificationtext;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jerrorvalid;
    // End of variables declaration//GEN-END:variables
}
