/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import opnsrc.fcih.trainrsys.backend.Employee;

/**
 *
 * @author keroles samer
 */
public class Adminn extends javax.swing.JFrame {

    /**
     * Creates new form Adminn
     */

   public static  Employee returned;
    AdminAddEmployee Adde;
    AddTrain Addt;
    int flag =-1;
    EmployeeTable fp ;
    TrainTable sp;
    GridBagLayout layout=new GridBagLayout();
    ubdateAnddelete UAD ;
    public Adminn() {
        
        initComponents();
        jPaneloftable.setVisible(false);
        fp = new EmployeeTable();
        sp = new TrainTable();
        jPaneloftable.setLayout(layout);
        GridBagConstraints c=new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        jPanel10.setVisible(false);
        returned=new Employee();
        jPaneloftable.add(fp,c);
        jPaneloftable.add(sp,c);
        fp.setVisible(false);
        sp.setVisible(true);
        Adde =new AdminAddEmployee();
        Addt =new AddTrain();
        setExtendedState(emolyee.MAXIMIZED_HORIZ);
        setResizable(false);
        JUpdateButton9.setEnabled(false);
        JdeletButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        CountainerPanal = new javax.swing.JPanel();
        JUpdateButton9 = new javax.swing.JButton();
        JListButton = new javax.swing.JButton();
        JdeletButton1 = new javax.swing.JButton();
        jRadioButton = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        JAddButton = new javax.swing.JButton();
        jidforsearch = new javax.swing.JTextField();
        jsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPaneloftable = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jerror = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CountainerPanal.setBackground(new java.awt.Color(153, 153, 153));
        CountainerPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JUpdateButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JUpdateButton9.setText("Update");
        JUpdateButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUpdateButtonActionPerformed(evt);
            }
        });
        CountainerPanal.add(JUpdateButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 146, -1));

        JListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JListButton.setText("List");
        JListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JListButtonActionPerformed(evt);
            }
        });
        CountainerPanal.add(JListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 148, -1));

        JdeletButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JdeletButton1.setText("Delete");
        JdeletButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdeletButton1ActionPerformed(evt);
            }
        });
        CountainerPanal.add(JdeletButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 144, -1));

        add.add(jRadioButton);
        jRadioButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton.setForeground(new java.awt.Color(248, 149, 32));
        jRadioButton.setText(" Employee");
        jRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActionPerformed(evt);
            }
        });
        CountainerPanal.add(jRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 119, 40));

        add.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(248, 149, 32));
        jRadioButton2.setText(" Train");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        CountainerPanal.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 119, 39));

        JAddButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JAddButton.setText("Add");
        JAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAddButtonActionPerformed(evt);
            }
        });
        CountainerPanal.add(JAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 148, -1));

        jidforsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidforsearchActionPerformed(evt);
            }
        });
        CountainerPanal.add(jidforsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 222, 29));

        jsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jsearch.setText("Search");
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });
        CountainerPanal.add(jsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 104, 29));
        CountainerPanal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 149, 32));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CountainerPanal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 86, -1));

        jPanel10.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CountainerPanal.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 193, -1, -1));

        javax.swing.GroupLayout jPaneloftableLayout = new javax.swing.GroupLayout(jPaneloftable);
        jPaneloftable.setLayout(jPaneloftableLayout);
        jPaneloftableLayout.setHorizontalGroup(
            jPaneloftableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPaneloftableLayout.setVerticalGroup(
            jPaneloftableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        CountainerPanal.add(jPaneloftable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 730, 190));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 149, 32));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin");
        CountainerPanal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 12, 270, 50));

        jerror.setForeground(new java.awt.Color(249, 149, 32));
        CountainerPanal.add(jerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 74, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/back.jpg"))); // NOI18N
        CountainerPanal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1050, 650));

        getContentPane().add(CountainerPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
        // TODO add your handling code here:
        
        if (!jidforsearch.getText().equals("")&&flag != -1) {
             Employee x = new Employee();
            returned = x.searchEmpById(Integer.parseInt(jidforsearch.getText()));
            if (returned.getUserName()> 0) {
              //setPanelData(returned);
              JUpdateButton9.setEnabled(true);
             JdeletButton1.setEnabled(true);
             jerror.setText("");
            } else {
               jerror.setText("Not Found ...!"); 
               
               
               
            }
        } else {
          jerror.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
          
        }         
    }//GEN-LAST:event_jsearchActionPerformed

    private void jidforsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidforsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidforsearchActionPerformed

    private void JAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAddButtonActionPerformed
        if(flag==1){
            Adde.setVisible(true);

        }
        else if(flag==0){
            Addt.setVisible(true);
        }else
        {
            jerror.setText("nothing choosen");
        }
    }//GEN-LAST:event_JAddButtonActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        fp.setVisible(false);
        sp.setVisible(true);
        flag=0;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonActionPerformed
        fp.setVisible(true);
        sp.setVisible(false);
        flag =1;
        
    }//GEN-LAST:event_jRadioButtonActionPerformed

    private void JdeletButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdeletButton1ActionPerformed
        UAD=new ubdateAnddelete(false, returned);
    }//GEN-LAST:event_JdeletButton1ActionPerformed

    private void JListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JListButtonActionPerformed
        // TODO add your handling code here:
        if(flag!=-1)
        {
            jPaneloftable.setVisible(true);
             jerror.setText("");
        
        }
        else{
            jerror.setText("there is missing radio button to enter ");
        }
    }//GEN-LAST:event_JListButtonActionPerformed

    private void JUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUpdateButtonActionPerformed
        UAD=new ubdateAnddelete(true, returned);
        UAD.setVisible(true);
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_JUpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CountainerPanal;
    private javax.swing.JButton JAddButton;
    private javax.swing.JButton JListButton;
    private javax.swing.JButton JUpdateButton9;
    private javax.swing.JButton JdeletButton1;
    public static javax.swing.ButtonGroup add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPaneloftable;
    private javax.swing.JRadioButton jRadioButton;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jerror;
    private javax.swing.JTextField jidforsearch;
    private javax.swing.JButton jsearch;
    // End of variables declaration//GEN-END:variables
}
