/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import opnsrc.fcih.trainrsys.backend.Train;
//import opnsrc.fcih.trainrsys.backend.train;

/**
 *
 * @author keroles samer
 */
public class emolyee extends javax.swing.JFrame {

    /**
     * Creates new form emolyee
     */
    Book_tickets bt;
    Mange_ticket ma;
    public emolyee() {
        initComponents();
        bt=new Book_tickets();
        ma =new Mange_ticket();
        setExtendedState(emolyee.MAXIMIZED_HORIZ);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_date = new javax.swing.JLabel();
        jLabel_source = new javax.swing.JLabel();
        jLabel_destination = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton_gettrain = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jMange = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Train ID", "Time", "Arrive Time", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 736, 90));

        jLabel_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_date.setForeground(new java.awt.Color(248, 149, 32));
        jLabel_date.setText("Date");
        getContentPane().add(jLabel_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 25));

        jLabel_source.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_source.setForeground(new java.awt.Color(248, 149, 32));
        jLabel_source.setText("Source");
        getContentPane().add(jLabel_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 70, 26));

        jLabel_destination.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_destination.setForeground(new java.awt.Color(248, 149, 32));
        jLabel_destination.setText("Destination");
        getContentPane().add(jLabel_destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 81, 26));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alex", "Cairo", "Aswan", "Matroh" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 170, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alex", "Cairo", "Aswan", "Matroh" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 170, 30));

        jButton_gettrain.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_gettrain.setText("GET  TRAIN");
        jButton_gettrain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_gettrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gettrainActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_gettrain, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 194, 30));

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 170, 30));

        jMange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMange.setText("Mange");
        jMange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMangeActionPerformed(evt);
            }
        });
        getContentPane().add(jMange, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 80, 40));

        jButton1.setText("reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/back.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMangeActionPerformed
        ma.setVisible(true);
    }//GEN-LAST:event_jMangeActionPerformed

    private void jButton_gettrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gettrainActionPerformed
        // TODO add your handling code here:
        addRowsTojTable();
    }//GEN-LAST:event_jButton_gettrainActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      bt.setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emolyee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emolyee().setVisible(true);
            }
        });
    }
public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[4];

        Train e = new Train();
        ArrayList<Train> trains = new ArrayList<Train>();

        trains= e.listTrains();

        for (Train x : trains) {
            if((jComboBox1.getSelectedItem()+"").equals(x.GetStart_Point())
                    && (jComboBox2.getSelectedItem()+"")
                            .equals(x.GetArraive_Point())){
            rowData[0] = x.GetTrain_ID();
            rowData[1] = x.GetTrain_Name();
            rowData[2] = x.GetArriveTime();
            rowData[3] = x.GetLeavingTime_sPoint();
          //  rowData[4] = x.gete();//get email
            //rowData[5] = x.getPassword();
         //   rowData[6] = x.getDateofbirt();
          
            model.addRow(rowData);
            }
    }


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_gettrain;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_destination;
    private javax.swing.JLabel jLabel_source;
    private javax.swing.JButton jMange;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
