/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import opnsrc.fcih.trainrsys.backend.*;
/**
 *
 * @author keroles samer
 */
public class EmployeeTable extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeTable
     */
    public EmployeeTable() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JEmployeeTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Phone", "Username", "Password", "DOB", "..."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JEmployeeTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 390));
    }// </editor-fold>//GEN-END:initComponents
public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) JEmployeeTable.getModel();
        Object rowData[] = new Object[6];

        Employee e = new Employee();
        ArrayList<Employee> Employees = new ArrayList<Employee>();

        Employees= e.listEmployees();

        for (Employee x : Employees) {
            rowData[0] = x.getUserName();
            rowData[1] = x.getName();
            rowData[2] = x.getGender();
            rowData[3] = x.getphone();
          //  rowData[4] = x.gete();//get email
            rowData[5] = x.getPassword();
         //   rowData[6] = x.getDateofbirt();
          
            model.addRow(rowData);
 
    }


}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JEmployeeTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

