/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import opnsrc.fcih.trainrsys.backend.*;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keroles samer
 */
public class TrainTable extends javax.swing.JPanel {

    /**
     * Creates new form TrainTable
     */
    public TrainTable() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTrainTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(46, 46, 46));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTrainTable.setBackground(new java.awt.Color(0, 204, 0));
        JTrainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "StartPoint", "LeavePoint", "ArriveTime", "LeaveTime", "Speed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTrainTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 400));
    }// </editor-fold>//GEN-END:initComponents
    public void addRowsTojTable() {
     DefaultTableModel model = (DefaultTableModel) JTrainTable.getModel();
        Object rowData[] = new Object[9];

        Train t = new Train();
        ArrayList<Train> Trains= new ArrayList<Train>();

        Trains = t.listTrains();

        for (Train x : Trains) {
            rowData[0] = x.GetTrain_ID();
            rowData[1] = x.GetTrain_Name();
            rowData[2] = x.GetStart_Point();
            rowData[3] = x.GetArraive_Point();
            rowData[4] = x.GetArriveTime();
            rowData[5] = x.GetLeavingTime_sPoint();
            rowData[6] = x.GetSpeed();
           

            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTrainTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

