/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import opnsrc.fcih.trainrsys.backend.Admin;
import opnsrc.fcih.trainrsys.backend.Employee;

/**
 *
 * @author h
 */
public class ubdateAnddelete extends javax.swing.JFrame {

    /**
     * Creates new form ubdateAnddelete
     */
    int oldid;
    Admin admin;
    int flag;
    boolean Gender;
    Employee e;
    public ubdateAnddelete(boolean  Choser,Employee newe) {
        initComponents();
           admin =new Admin();
           e=new Employee();
           oldid=newe.getUserName();
           JEmployeeID.setText(newe.getUserName()+"");
           JEmployeeName.setText(newe.getName());
           JEmployeePassword.setText(newe.getPassword());
           JEmployeePhone.setText(newe.getphone()+"");
           
           JEmployeeAdress.setText(newe.getAdress());
           if(Choser){
               jDeleteButtonemp.setEnabled(false);
           } 
           else{
               jupdateButtonemp.setEnabled(false);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JEmployeeID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JEmployeeName = new javax.swing.JTextField();
        JEmployeeJoinDate = new com.toedter.calendar.JDateChooser();
        JEmployeePassword = new javax.swing.JPasswordField();
        JEmployeePhone = new javax.swing.JTextField();
        JEmployeeAdress = new javax.swing.JTextField();
        jMale = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        JFemale = new javax.swing.JRadioButton();
        jupdateButtonemp = new javax.swing.JButton();
        jDeleteButtonemp = new javax.swing.JButton();
        jerrorvalid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JEmployeeID.setForeground(new java.awt.Color(255, 51, 51));
        JEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 149, 32));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 63, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 149, 32));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 63, -1));

        JEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeeNameActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 150, 30));
        getContentPane().add(JEmployeeJoinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 150, 30));

        JEmployeePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, 30));

        JEmployeePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeePhoneActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 150, 30));

        JEmployeeAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmployeeAdressActionPerformed(evt);
            }
        });
        getContentPane().add(JEmployeeAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 150, 30));

        jMale.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(jMale);
        jMale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMale.setForeground(new java.awt.Color(248, 149, 32));
        jMale.setText(" Male");
        jMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaleActionPerformed(evt);
            }
        });
        getContentPane().add(jMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 150, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(248, 149, 32));
        jLabel20.setText("gender");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 70, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(248, 149, 32));
        jLabel18.setText("Phone");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 63, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(248, 149, 32));
        jLabel17.setText("Password");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 149, 32));
        jLabel1.setText("joindate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 63, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(248, 149, 32));
        jLabel19.setText("Address");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 63, 20));

        JFemale.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(JFemale);
        JFemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JFemale.setForeground(new java.awt.Color(248, 149, 32));
        JFemale.setText(" female");
        JFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFemaleActionPerformed(evt);
            }
        });
        getContentPane().add(JFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 150, 30));

        jupdateButtonemp.setText("Update");
        jupdateButtonemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateButtonempActionPerformed(evt);
            }
        });
        getContentPane().add(jupdateButtonemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jDeleteButtonemp.setText("Delete");
        jDeleteButtonemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonempActionPerformed(evt);
            }
        });
        getContentPane().add(jDeleteButtonemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        jerrorvalid.setForeground(new java.awt.Color(249, 149, 32));
        getContentPane().add(jerrorvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 150, 30));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logiiiin.jpg"))); // NOI18N
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 930, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeeIDActionPerformed
        if(Integer.parseInt(JEmployeeID.getText())<0){
            jerrorvalid.setText("invalid ID");
            JEmployeeID.setText("");
        }
        else{
            e.setUserName(Integer.parseInt(JEmployeeID.getText()));
            jerrorvalid.setText("");
        }
    }//GEN-LAST:event_JEmployeeIDActionPerformed

    private void JEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeeNameActionPerformed
        e.setName(JEmployeeName.getText()+"");
    }//GEN-LAST:event_JEmployeeNameActionPerformed

    private void JEmployeePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeePasswordActionPerformed
        if((JEmployeePassword+"").length()<8) {
            jerrorvalid.setText("invalid PASSWORD");
            JEmployeePassword.setText("");
        }
        else{
            e.setPassword(JEmployeePassword.getText()+"");
            jerrorvalid.setText("");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_JEmployeePasswordActionPerformed

    private void JEmployeePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeePhoneActionPerformed
        if(JEmployeePhone.getText().length()!=11) {
            jerrorvalid.setText("invalid phone");
            JEmployeePhone.setText("");
        }
        else{
            e.setPhone(JEmployeePhone.getText());
            jerrorvalid.setText("");
        }
    }//GEN-LAST:event_JEmployeePhoneActionPerformed

    private void JEmployeeAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmployeeAdressActionPerformed
        e.setAdress(JEmployeeAdress.getText());
    }//GEN-LAST:event_JEmployeeAdressActionPerformed

    private void jMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaleActionPerformed
        // TODO add your handling code here:
        flag=1;
        Gender=true;
        e.setGender(Gender);
    }//GEN-LAST:event_jMaleActionPerformed

    private void JFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFemaleActionPerformed
        // TODO add your handling code here:
        flag=2;
        Gender=false;
        e.setGender(Gender);
    }//GEN-LAST:event_JFemaleActionPerformed

    private void jDeleteButtonempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonempActionPerformed
admin.deleteEmployee(oldid);
        
       
     
    }//GEN-LAST:event_jDeleteButtonempActionPerformed

    private void jupdateButtonempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateButtonempActionPerformed
        admin.updateEmployee(oldid, e);
    }//GEN-LAST:event_jupdateButtonempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ubdateAnddelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ubdateAnddelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ubdateAnddelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ubdateAnddelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ubdateAnddelete().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JEmployeeAdress;
    private javax.swing.JTextField JEmployeeID;
    private com.toedter.calendar.JDateChooser JEmployeeJoinDate;
    private javax.swing.JTextField JEmployeeName;
    private javax.swing.JPasswordField JEmployeePassword;
    private javax.swing.JTextField JEmployeePhone;
    private javax.swing.JRadioButton JFemale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jDeleteButtonemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jMale;
    private javax.swing.JLabel jerrorvalid;
    private javax.swing.JButton jupdateButtonemp;
    // End of variables declaration//GEN-END:variables
}
